---
title: "Green Actions"
format:
    dashboard:
        nav-buttons: [github]
        github: https://github.com/green-actions
theme: minty
---

```{r setup, include = FALSE}
library(dplyr)
library(ggplot2)
library(purrr)
```

```{r}
#| label: load-data
#| message: false


### Read in data here
actions_data <- read.csv("../data/green-actions-workflows.csv")

duration_quant <- as.numeric(quantile(actions_data$duration))
```

```{r}
#| label: calculate statistics
#| message: false

get_colour <- function(time_df) {

  ## Get quantiles of the data
  p_firstblock <- "primary"
  p_secondblock <- "warning"
  p_thirdblock <- "secondary"
  p_fourthblock <- "danger"

  color <- mutate(time_df, color = case_when(
    time_df$duration <= duration_quant[2] ~ p_firstblock,
    (time_df$duration > duration_quant[2]) & (time_df$duration <= duration_quant[3]) ~ p_secondblock,
    (time_df$duration > duration_quant[3]) & (time_df$duration <= duration_quant[4]) ~ p_thirdblock,
    time_df$duration > duration_quant[4] ~ p_fourthblock))
  return(color)
}

# Group by branch and calculate summary statistics for each branch, then assign a colour based on the duration
workflow_duration <- actions_data |>
  group_by(workflow_name) |>
  summarise(duration = mean(duration), n = n()) |>
  get_colour()

# Filter to workflows with multiple runs for comparison
workflows_run_multiple <- filter(workflow_duration, n>1)

actions_to_summarise <- actions_data |>
  filter(workflow_name %in% workflows_run_multiple$workflow_name)

## Get the colour for each workflow and arrange by start time
model_summary <- actions_to_summarise  |>
  split(actions_to_summarise$workflow_name) |>
  purrr::map(get_colour) |>
  purrr::map(arrange, start_time) |>
  purrr::map(mutate, order_col = row_number())

# Fit a linear model to the start time to identify if the timing of the actions is
# increasing or decreasing over time.
coef_by_workflow <- model_summary |>
  lapply(function(df) lm(duration ~ order_col, data = df)) |> lapply(coef)

```

## Row {height="30%"}

```{r}
#| content: valuebox
#| title: "Time for Linting workflow"
arrow_icon <- unname(ifelse(coef_by_workflow$Linting[2]<0, "arrow-down", "arrow-up"))
list(
  icon = arrow_icon,
  color = model_summary$Linting$color[nrow(model_summary$Linting)],
  value = model_summary$Linting$duration[nrow(model_summary$Linting)]
)

```


```{r}
#| content: valuebox
#| title: "Time for Links workflow"


arrow_icon <- unname(ifelse(coef_by_workflow$Links[2]<0, "arrow-down", "arrow-up"))
list(
  icon = arrow_icon,
  color = model_summary$Links$color[nrow(model_summary$Links)],
  value = model_summary$Links$duration[nrow(model_summary$Links)]
)

```

```{r}
#| content: valuebox
#| title: "Time for Copilot code review workflow"
arrow_icon <- ifelse(coef_by_workflow$`Copilot code review`[2]<0, "arrow-down", "arrow-up")
list(
  icon = unname(arrow_icon),
  color = model_summary$`Copilot code review`$color[nrow(model_summary$`Copilot code review`)],
  value = model_summary$`Copilot code review`$duration[nrow(model_summary$`Copilot code review`)]
)
```

## Row {height="100%"}

```{r}
#| title: Run duration for different branches
#| fig-width: 15
#| fig-height: 12
#| out-width: "100%"
#| fig-responsive: true
# Put in the bubbleplot

workflow_start_time <- as.POSIXct(actions_data$workflow_start_time, format = "%H:%M:%S")

p <- ggplot2::ggplot(actions_data) +
  ggplot2::geom_point(aes(x = start_time, y = workflow_name, size = duration, color = branch)) +
  xlab("Workflow start time") +
  ylab("Workflow name") +
  ggtitle("Run duration: workflow name against timestamp for different branches") +
  theme_bw() + theme(axis.text.x = element_text(angle = 90))

p
```
